/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_starry_douban_jni_JNISample */

#ifndef _Included_com_starry_douban_jni_JNISample
#define _Included_com_starry_douban_jni_JNISample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_starry_douban_jni_JNISample
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_starry_douban_jni_JNISample_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
